name: main-ci

on:
  push:

jobs:
  docker-build-and-push-main:
    uses: ./.github/workflows/docker-build-and-push.template.yml

  docker-build-and-push-builder:
    uses: ./.github/workflows/docker-build-and-push.template.yml
    with:
      context: builder-image

  
